name: "mace-inter2"
train_file: "inter-training.xyz"
valid_fraction: 0.1
E0s: '{42: 0., 16: 0.}'
model: "MACE"
hidden_irreps: "32x0e + 32x1o"
r_max: 7.0
batch_size: 10
max_num_epochs: 50
ema: True
ema_decay: 0.99
amsgrad: True
default_dtype: "float64"
device: cuda
swa: True
max_ell: 2
restart_latest: True

